global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']




#  This config is referenced by install_prometheus.sh, and you may want to copy this file into /etc/prometheus/ during setup.
